name: Commitlint
on:
  push:
    branches-ignore: [development, master]
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: lts/gallium
          cache: npm
      - run: npm install -g commitlint @commitlint/config-conventional
  commitlint:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: lts/gallium
          cache: npm
      - run: commitlint --from ${{ github.event.before }} --to ${{ github.event.after }}
