name: Commitlint
on:
  push:
    branches-ignore: [development, master]
jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: lts/gallium
      - run: npm install -g commitlint @commitlint/config-conventional
      - run: commitlint --from ${{ github.event.commits[0].id }} --to ${{ github.event.after }}
