name: Lint check
on:
  pull_request:
    branches: [development, master]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: 1.1.13
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'poetry'
      - run: poetry install
      - run: poetry run poe pylint-check
