name: CI
on:
  pull_request:
    branches: [development, master]
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['3.9', '3.10.5', '3.10.6']
    steps:
      - uses: actions/checkout@v3
      - uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: 1.15
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}
          cache: 'poetry'
      - run: poetry install
  format:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: 1.2.0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.6'
          cache: 'poetry'
      - run: poetry install
      - run: poetry run poe black-check
  lint:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: 1.2.0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.6'
          cache: 'poetry'
      - run: poetry install
      - run: poetry run poe pylint-check
  ci:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: 1.2.0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.6'
          cache: 'poetry'
      - run: poetry install
      - name: Poetry test
        run: poetry run test --cov
